# Mutualism with multicellular organisms

Notes and literature search based on several review papers below. These notes are designed for an open-book exam, where I can return to a section of a review for more examples or revisit the cited work for more details. These notes may be direct quotes or phrases from the reviews, the below information is not my own work or research.

[Dittami et al 2021](https://peerj.com/articles/10911/): A community perspective on the concept of marine holobionts: current status, challenges, and future directions

[Wilkins et al 2019](https://journals.plos.org/plosbiology/article?rev=2&id=10.1371/journal.pbio.3000533): Host-associated microbiomes drive structure and function of marine ecosystems.

## Symbiosis {-}

Definitions for microbiome, symbiosis, ecosystem functions, and health status of microbes are well described in Wilkins et al 2019 (link above).

More in-depth descriptions and diagrams of the Coral Holobiont found [here](https://github.com/emmastrand/EmmaStrand_Notebook/blob/master/Comprehensive-Exams/Roxanne-exam/Coral-Holobiont.md).

**Hologenome theory**

This suggests that natural selection acts at the level of the holobiont and its hologenome.

**Marine symbionts and holobionts on ecological processes**:

**'Ecosystem engineers'**

= corals, deep-sea mussels, hydrothermal vent tubeworms -- all contribute to primary productivity and create the structural habitat and nutrient resources for foundation of ecocystems (Wilkins et al; Seemann et al 2018). All of which deeply relies on symbiosis with other organisms to be the basis of that ecosystem.

**Sustaining populations and diversity**:

Host organisms can enhance dispersion rate of microbiota (Troussellier et al 2017) and act as bio-vectors like marine birds (Bouchard Marmen et al 2017). Host-driven dispersal of microbiota.

Hosts can sustain rare species by providing a nutrient rich environment that otherwise wouldn't exist and this favors the growth of microbiomes (5 citations in Dittami et al).  
- reduced and anoxic sediments: lucinid clams, stilbonematid nematodes, gutless oligocahetes (examples in Wilkins et al)  
- hydrothermal vents: giant tube worm and deep-sea mussels (examples in Wilkins et al)

**Global biogeochemical cycles**

Microbes are drivers of global biogeochemical cycles; including mass amounts of nitrogen fixation (several examples in Dittami et al). Functions as sinks and sources of nutrients for the entire ecosystem (corals and sponges for reefs).  
- "Sponge loop": recycles dissolved organic matter and makes it available to higher trophic levels via detritus.  
- Alternatively, in coastal areas: bivalves that host methanogenic archaea = increase benthic methane efflux

Thus **expanding metabolic capacity** with new abilities via biochemical machineries (anaerobic and aerobic pathways) (Dittami et al has examples):  
- production of essential amino acids, photosynthesis, and/or chemosynthesis  
- could enhance resilience to environmental change (Van Oppen papers; several citations in Dittami et al)  
- Or cross biotope boundaries (Woyke et al 2006) or colonize extreme environments (Bang et al 2018)  

Biotope boundaries: biotope = an environment or habitat. If a biotope boundary is crossed, then the organism is inhabiting a new environment that they wouldn't otherwise cross.

**Nutritional value**  
- Bacteria in the gut of surgeonfishes produce enzymes that allow hosts to digest complex polysaccharides, enabling the host fish to feed on tough, leathery red and brown macroalgae (Wilkins et al example: Ngugi et al 2017)  
- Gammaproteobacteria nourish ciliate host and recycle acetate and propionate (low value cellular waste products from host) into biomass (Wilkins et al example: BKB et al 2019);  
- Wilkins et al has a couple other examples of nutritional value symbioses

**Reproduction and host development**

- Several examples of settlement cues by microbiota in Wilkins et al and influencing growth of host: some microbiota can secrete phytohormones  
- Host development classic example of the squid and bacteria

**Establishment of symbiosis: Vertical and Horizontal Transmission**

Bivalves transmit part of microbiota maternally (Bright and Bulgheresi 2010; Funkhouser and Bordenstein 2013)

Mixed modes or intermediate modes are common (pseudo-vertical -- horizontal acquisition frequently involves symbionts of parental origin) (Bjork et al 2019)

During either mode of transmission, selection occurs by the host or components of the microbiome and establishes the internal/associated community that is then separate from the surrounding environment. This can lead to co-evolution and/or 'phylosymbiosis' as described below.

**Co-evolution / 'phylosymbiosis'**

Assembly of a community: actively selecting a community, ecological drift, dispersal and evolutionary diversification

**Actively selecting a community**

The host immune system plays a large role in establishing symbiotic relationship: secretion of antimicrobial peptides (examples listed in Dittami et al) is seen to perform this selection.

Microbial gardening: chemically mediated act of frequently releasing growth-enhancing or inhibiting chemicals or metabolites that favor the development of a microbial community beneficial to the host. (Saha and Weinberger 2019):  
- Examples from Dittami et al: seaweeds do this and facilitate normal morphogenesis and increase disease resistance; seaweeds and corals structure surface-associated microbiome by producing chemo-attractants and anti-bacterial compounds  

**Dispersal**

A marine environment has high connectivity (because of factors like high water flow), and therefore high microbial flow and connectivity. There is high dispersion and drift rather than limited dispersal.

**Diversification**

Driven by horizontal acquisition of genes or co-evolution or adaptation to host selection (Dittami et al)

**Co-speciation** is very difficult to prove: few studies = Peek et al 1998; Lanterbecq, Rouse & Eeckhaut 2010

## Dysbiosis {-}

In corals, this can happen with either microbiota or endosymbionts: Biology Coral Bleaching more info [here](https://github.com/emmastrand/EmmaStrand_Notebook/blob/master/Comprehensive-Exams/Putnam-exam/Coral-Bleaching.md) - only covers endosymbiont dysbiosis.

Common to see higher variability in composition than those of healthy organisms (Dittami et al).

**"Anna Karenina Principle"**

This is the idea that a deficiency in any one of a number of factors dooms an endeavor to failure. Consequently, a successful endeavor is one for which every possible deficiency has been avoided. The Anna Karenina principle was popularized by Jared Diamond in his 1997 book Guns, Germs and Steel. Diamond uses this principle to illustrate why so few wild animals have been successfully domesticated throughout history, as a deficiency in any one of a great number of factors can render a species undomesticable. (Wikipedia - obviously do not cite this on exam; just for background reference)

The principles describes when several factors can cause a system to fail, but only a narrow range of parameters characterizes a working system; based on the first sentence of Leo Tolstoy’s ‘‘Anna Karenina’’ (1878): ‘‘Happy families
are all alike; every unhappy family is unhappy in its own way’’ (Zaneveld, McMinds & Vega Thurber, 2017).

Zanedveld, McMinds, Vega Thurber 2017: description of principle  
Marzinelli et al 2015: exceptions to this principle

**"Rasputin effect"**

Where symbionts that were once benign endosymbionts become detrimental or parasitic to the host because of environmental perturbations, reduction in immune system response to food deprivation, co-infections (Overstreet and Lotz 2016 for description).

This is exactly what happens in corals as described above. Baker et al 2018 describes this well too.

**Methodologies**

"Omics" techniques: metagenomics, single-cell genomics, metatranscriptomics, metaproteomics  
- can determine functions carried out by different components of the holobionts

Metaproteomics and stable isotope fingerprinting - metabolism of single lineages within holobiont (see Kleiner et al 2018 for example; Dittami et al)

Meta-metabolomics - chemical interactions between partners

In-vivo and in-situ imaging techniques with metabolomicomics - small-scale spatial and qualitive information (origin, distribution, concentration of molecule or nutrient); contribution of each partner (Dittami et al)  
- Geier et al 2020 for more

Stable isotope labelling and chemical imaging (mass spec imaging: secondary ion mass spec or matrix-assisted laser desoprtion ionization; synchrotron X-ray fluorescence) - metabolic exchange between different compartments of holobiont  
- Musat et al 2016; Raina et al 2017 for examples

Three-dimensional electron microscopy - what extent different components of a holobiont are physically integrated (Colin et al 2017; Decelle et al 2019 for examples):  
- Could this be used in determining physical presence of partners? Depends on what components means above?

Single-cell omics - growth requirements of organisms (Gutleben et al 2018)

**Conservation**

Dittami et al has a good overview of how this information can be integrated into conservation plans.
